### ISSUE TITLE
Replace the Intercom feature in app support with email

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/support#1]
In stead of having a live chat, we should have one channel for incoming support requests. Support button in the app should lead to the following message:

Please use the Support Form to receive help from our team members. Filling up the form is going to help our team to resolve your issue fast and effective.

* Full name
* Email address
* On what subject do you need assistance? 
(choices)
  - ThreeFold Tokens
  - Blockchain Node
  - Farming
  - Purchasing capacity
  - ThreeFold App
  - Other (specify)
* What is your wallet address? (if applicable)
* What is your ThreeFold Farm ID? (if applicable)
* Upload screenshot of issue (if applicable) 
* Please explain what it is you need assistance with. 

SEND

Send button should send this form to support@threefold.tech

**Comment by sabrinasadik** [comment]
See tf_app issue #384 - https://github.com/threefoldfoundation/tf_app/issues/384

**Comment by Pishoy** [comment]
closing it as ticket has been moved to correct repo
