### ISSUE TITLE
Bettertoken Node not working (Bart Van Houdt)

### ISSUE THREAD

**Issue by joris19755** [threefoldtech/support#3]
Bart Received his node but USB key was missing, he created the USB key with our support and got his farm up and running. Upon reception of his node the MAC Address was not indicated anywhere . After couple of weeks it stopped working .

**Comment by joris19755** [comment]
I collected the node (without USB key) (9/1/2019), Bart and I meat in Brussel, Bart found it easier to meet me than sending the node back. Will test it out tonight

**Comment by joris19755** [comment]
![bvh](https://user-images.githubusercontent.com/44951133/50927176-4989f900-1457-11e9-86fd-1109185cfe0b.jpg)
bvh node online, but not showing in capacity.threefold.com https://capacity.threefoldtoken.com/?cru=0&mru=0&hru=0&sru=0&country=&farmer=3053+new+farmland+bvh

**Comment by delandtj** [comment]
hmmm. it's not booted with the support flag. difficult to see then.

**Comment by joris19755** [comment]
FarmerID=
eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhenAiOiJ0aHJlZWZvbGQuZmFybWVycyIsImV4cCI6MTU0MTc1NzgxNCwiaXNzIjoiaXRzeW91b25saW5lIiwicmVmcmVzaF90b2tlbiI6ImpIVUtFT2NiYTd1dlF2czNXRzloRkVWbFIxc2IiLCJzY29wZSI6WyJ1c2VyOm1lbWJlcm9mOjMwNTMgbmV3IGZhcm1sYW5kIGJ2aCJdLCJ1c2VybmFtZSI6ImJhcnRfdmFuaG91ZHRfMSJ9.Erl7mJmjR7ETSViHVBtZBRV3mZ_7gYP_8P-qaDUgR1ekQQS9JUb5_3aob1TTYV5C0LI1fM0rQ7cJMZT9R35GZ3IiwmcnFBkV9p5SJoCaizBIGpMN2FzgCWk0QxZpnPFJ

**Comment by zaibon** [comment]
@joris19755 can you please leave the node running, and letting me know when it up.

I tried to investigate it, but it seems to be offline at the moment. thanks

**Comment by joris19755** [comment]
Maxux, found out that ...
"looks like robot doesn't start
Jwt expired, the farmerid is expired
Owner needs to recreate a jwt on the capacity server."

BVH created a new farmer ID, I created a new USB stick and bvh farm is up and running
![image](https://user-images.githubusercontent.com/44951133/51001994-313adc80-1532-11e9-9c9a-67c2c437767b.png)
