### ISSUE TITLE
Blockchain (zero-node) Node Offline (Marc Meire)

### ISSUE THREAD

**Issue by joris19755** [threefoldtech/support#4]
From: "Marc Meire" <info@meiredebal.be>
Subject: RE: Fw: [Norton AntiSpam]
Date: 7 January 2019 at 11:15:46 GMT+1
To: "'Jacques Staelens'" <jstaelen@racktivity.com>
Cc: "'Sabrina from ThreeFoldToken'" <sabrina.sadik@threefoldtoken.intercom-mail.com>

Beste Jacques,
 
Vooreerst mijn beste wensen voor 2019  !
 
Mijn “node “ is volgens mijn app offline gegaan op 6/11/2018.
 
Sedertdien al verschillende keren aan en af gezet maar geen resultaat.
 
Volgens Telenet zijn de modems in orde…
 
Kan ik nog iets anders proberen?
 
 
Mijn email-adres is ondertussen veranderd naar info@meiredebal.be
 
Vraagje : Mocht ik mijn tokens willen verkopen , wat is de te volgen procedure en hoeveel is de huidige waarde?

**Comment by zaibon** [comment]
node id : `00e04c6805f1`
Serial number: `HYSZ170000773`

**Comment by zaibon** [comment]
@joris19755 can we get an english translation of this please ?

**Comment by Pishoy** [comment]
here is issue about reporting that blockchain node is down
https://github.com/threefoldfoundation/tfchain/issues/278

**Comment by Pishoy** [comment]
closing now as no feedback from customer ..
