### ISSUE TITLE
Running a node on mac

### ISSUE THREAD

**Issue by tftmesh** [threefoldtech/support#6]
Hi all, 
So my usb is set up on EFI from the zero-OS Bootstrap, do I have to change @ step 4 to USB?

**Comment by maxux** [comment]
What kind of Mac ? What are you trying to do ?

**Comment by tftmesh** [comment]
Mac book late 2011,
4 GB 1333 MHz DDR3
2.4 Ghz core i5
499 GB
I'm trying to run the node to farm from it, is that possible?

**Comment by tftmesh** [comment]
Ok I got (EFI boot) usb pic on startup
Clicked,
Now it says on the black screen written in white(Initializing network devices...)
Is that good?

**Comment by maxux** [comment]
Can you provide screenshot of what's happening ?
Does something happens after the Initializing network devices ?

This seems a good start, the bootloader start, but it should then download the kernel. Is your Mac connected to internet over ethernet wire ? This is needed (no wifi).

**Comment by tftmesh** [comment]
![img_7027](https://user-images.githubusercontent.com/46674334/51111119-f673c580-180b-11e9-92b7-6776fba56b7e.JPEG)
got to have ethernet?

**Comment by siddiquagig** [comment]
@tftmesh , can you please send me farm-id , farm-name you registered, it could be an image issue.

Did you use the development branch in the first step ?

Also if possible share your telegram-id , mine is ```ahmedsidd``` , to have a better interactive communication

**Comment by tftmesh** [comment]
Farm ID: tftmesh
I used (development) the one under master, I guess with no branch

**Comment by siddiquagig** [comment]
@tftmesh , as discussed on telegram , this a network issue as as your MAC is not getting a IP from the router , can you please connect lan to a DHCP enabled router.

**Comment by siddiquagig** [comment]
The farmer arranged a new router and his MAC started downloading the ZeroOS image , but it gets stuck at this(see attached), we tried many branches (development, master, rc.1.5.0) but same issue.

![tft image 2](https://user-images.githubusercontent.com/25789724/51601989-42ff8500-1f1f-11e9-85d1-f93cefdedbf1.jpg)

**Comment by maxux** [comment]
It looks like the kernel is booting but then stuck on something. It's probably linux kernel configuration which is missing something or configuration on the Mac. I'll take a look.

**Comment by Pishoy** [comment]
moving it to https://docs.grid.tf/threefold/org_support/issues
