### ISSUE TITLE
Set Up farm but node does not show up on capacity.threefoldtoken.com

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/support#8]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/18591016/51258543-83ed1c00-19aa-11e9-9341-272d8514966a.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/18591016/51258556-8ea7b100-19aa-11e9-808d-da66cd5a1292.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/18591016/51258568-96ffec00-19aa-11e9-9127-c45a0ba87beb.png">
see above images of current status. thanks for your help

**Comment by Pishoy** [comment]
```
In [58]: ncl.kernel_args
Out[58]: 
{'01"': '',
 'console': 'tty1',
 'consoleblank': '0',
 'earlyprintk': 'serial,ttyS1,115200n8',
 'intel_iommu': 'on',
 'kvm-intel.nested': '1',
 'loglevel': '7',
 'organization': '"woid',
 'support': '',
 'zerotier': 'c7c8172af1f387a6'}
```
as it shown from above output you did not set the ` Farmer ID` when generating your image, please set it when creating your image and boot node again

**Comment by andhartl** [comment]
did this. still not showing up:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/18591016/51271419-ccff9900-19c7-11e9-883e-99b3e764b829.png">

**Comment by zaibon** [comment]
In the farmer id field. Just pass the ID without 'farmer_id' prefix
the color of the border should be green, not red.

**Comment by andhartl** [comment]
works. thanks for your help. will change farmer id usage in how to guide accordingly
