### ISSUE TITLE
Vienna Cherry Chapter Node not visible on capacity.threefoldtoken.com

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/support#9]
* Andreas Hartl, Hans Kastenhofer for Vienna Cherry Chapter
* andreas@threefoldtoken.com
* farming
zero os seems to work but node not visible on directory. see pic. pls help
![vccv2301_boot](https://user-images.githubusercontent.com/18591016/51678216-05146680-1fdc-11e9-9413-07e3adfa805f.PNG)

**Comment by sabrinasadik** [comment]
Resolved according to @andhartl

**Comment by andhartl** [comment]
they used the wrong zero tier id. once corrected node showed up on capacity.threefoldtoken.com
